server:
  port: 8088
## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 935171397@qq.com #发送邮件的邮箱地址
    password:  blubxkyrddjabbii #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
#    port: 465 #端口号465或587
    from: 935171397@qq.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
person:
  list:
    # 我
    - 935171397@qq.com
    # 猪皮
    - 1483682805@qq.com
    # 弟弟
    - yuejiayu123456@163.com
    # 远旭
    - 2581745851@qq.com
    # 室长
#    - 2214011302@qq.com